# Normal sku 50 task with common setting.
# All skus are selected from sku2307 with minimum fluctuation demand.
env:
  mode:
    - name: train
      start_date: 2018/8/1
      end_date: 2019/5/27
      random_interception: True
    - name: validation
      start_date: 2019/5/28
      end_date: 2019/9/4 
    - name: test
      start_date: 2019/9/5
      end_date: 2019/12/13
  horizon: 100
  lookback_len: 21
  integerization_sku: True
  warmup: replenish_by_last_demand
  sku_list: ReplenishmentEnv/data/sku2778/sku50.smooth_demand.sku_list.csv

facility:
  - name: store3
    initial_balance: 0
    capacity: 5000
    unit_storage_cost: 0.0001
    accept_sku: equal_accept
    upstream: super_vendor
    downstream: consumer
    sku:
      dynamic_data:
        - name: procurement_cost
          file: ReplenishmentEnv/data/sku2778/sku2778.store2.selling_price.csv
        - name: selling_price
          file: ReplenishmentEnv/data/sku2778/sku2778.store3.selling_price.csv
        - name: demand
          file: ReplenishmentEnv/data/sku2778/sku2778.demand.csv
      static_data: ReplenishmentEnv/data/sku2778/sku2778.store3.info.csv
      shared_data:
        order_cost: 10
        volume: 1
        basic_holding_cost: 0.0025
        backlog_ratio: 0

profit:
  profit_function: reward2
  excess_ratio: 0.5

reward:
  mode: same_as_profit

action:
  mode: demand_mean_continuous

output_state:
  current_state:
    [selling_price, procurement_cost, vlt, volume, 
    order_cost, replenish, excess, in_stock, in_transit]
  lookback_state:
    [demand]