# Normal sku 50 task with common setting.
# All skus are selected from sku2307 with minimum fluctuation demand.
env:
  mode:
    - name: train
      start_date: 2018/8/1
      end_date: 2019/5/27
      random_interception: True
    - name: validation
      start_date: 2019/5/28
      end_date: 2019/9/4 
    - name: test
      start_date: 2019/9/5
      end_date: 2019/12/14
  horizon: 100
  lookback_len: 21
  integerization_sku: True
  storage_capacity: 5000
  initial_balance: 0
  warmup: replenish_by_last_demand
  sku_list: ReplenishmentEnv/data/sku2778/sku50.smooth_demand.sku_list.csv

facility:
  - name: store1
    upstream: super_vendor
    downstream: store2
    sku:
      dynamic_info:
        - name: procurement_cost
          file: ReplenishmentEnv/data/sku2778/sku2778.super_vendor.selling_price.csv
        - name: selling_price
          file: ReplenishmentEnv/data/sku2778/sku2778.store1.selling_price.csv
      static_info: ReplenishmentEnv/data/sku2778/sku2778.store1.info.csv
      shared_info:
        order_cost: 10
        volume: 1
        storage_cost: 0.0025
        holding_cost_ratio: 0.00002
  - name: store2
    upstream: store1
    downstream: store3
    sku:
      dynamic_info:
        - name: procurement_cost
          file: ReplenishmentEnv/data/sku2778/sku2778.store1.selling_price.csv
        - name: selling_price
          file: ReplenishmentEnv/data/sku2778/sku2778.store2.selling_price.csv
      static_info: ReplenishmentEnv/data/sku2778/sku2778.store2.info.csv
      shared_info:
        order_cost: 10
        volume: 1
        storage_cost: 0.0025
        holding_cost_ratio: 0.00002
  - name: store3
    upstream: store2
    downstream: consumer
    sku:
      dynamic_info:
        - name: procurement_cost
          file: ReplenishmentEnv/data/sku2778/sku2778.store2.selling_price.csv
        - name: selling_price
          file: ReplenishmentEnv/data/sku2778/sku2778.store3.selling_price.csv
      static_info: ReplenishmentEnv/data/sku2778/sku2778.store3.info.csv
      shared_info:
        order_cost: 10
        volume: 1
        storage_cost: 0.0025
        holding_cost_ratio: 0.00002

profit:
  profit_function: reward2
  backlog_ratio: 0
  excess_ratio: 0.5

reward:
  mode: same_as_profit

action:
  mode: demand_mean_continuous

output_state:
  current_state:
    [selling_price, procurement_cost, vlt, volume, 
    order_cost, replenish, excess, in_stock, in_transit]
  lookback_state:
    [demand]