# Normal 58 skus task with common setting.
env:
  mode:
    - name: train
      start_date: 2011/01/01
      end_date: 2011/10/31
      random_interception: True
    - name: validation
      start_date: 2011/11/01
      end_date  : 2011/11/30
    - name: test
      start_date: 2011/12/01
      end_date  : 2011/12/31
  horizon: 100
  lookback_len: 21
  integerization_sku: True
  capacity: 5800
  initial_balance: 0
  warmup: replenish_by_last_demand
  sku_list: ReplenishmentEnv/data/sku58/sku58.sku_list.csv

facility:
  - name: store
    initial_balance: 0
    capacity: 5000
    unit_storage_cost: 0.0001
    accept_sku: equal_accept
    upstream: super_vendor
    downstream: consumer
    sku:
      dynamic_data: 
        - name: demand
          file: ReplenishmentEnv/data/sku58/sku58.demand.csv
      static_data: ReplenishmentEnv/data/sku58/sku58.info.csv
      shared_data:
        order_cost: 10
        volume: 1
        holding_cost: 0.0025
        backlog_ratio: 0

profit:
  profit_function: reward2
  excess_ratio: 0.5

reward:
  mode: same_as_profit

action:
  mode: demand_mean_continuous

output_state:
  current_state:
    [selling_price, procurement_cost, vlt, volume, 
    order_cost, replenish, excess, in_stock, in_transit]
  lookback_state:
    [demand]